### PR TITLE
docker: adjustable library versions

### PR DESCRIPTION
**Pull request by Snider**
The old boost repo was slow, so I moved to Sourceforge; this change lets you compile using different lib versions from the build command. Also, all the arguments are at the top of the Dockerfile for easier maintenance.

Added a GitHub workflow to run the docker build on push & pull_request with Github Actions.

```
docker build --build-arg OPENSSL_VERSION_DOT=1.1.1n --build-arg OPENSSL_HASH=40dceb51a4f6a5275bde0e6bf20ef4b91bfc32ed57c0552e2e8e15463372b17a -f utils/docker/Dockerfile .
```

### CODE REVIEW

**Comment by cryptozoidberg** [comment]
@Snider Hey, thanks for contribution! Is there any chance to have a quick chat over those changes? Are you in discord?

**Comment by sowle** [comment]
I checked the Dockerfile, looks good, works good.
@Snider, thank you for the contribution!

**Comment by Snider** [comment]
> @Snider Hey, thanks for contribution! Is there any chance to have a quick chat over those changes? Are you in discord?

Hey, yea sure, I ported over some of my work from last year on a cryptonote CC build container.

Snider.lthn#8193 / snider@lt.hn / http://discord.lt.hn 

> I checked the Dockerfile, looks good, works good. @Snider, thank you for the contribution!

I've got the code someplace to either compile from a clone or take the local files and build to the host's build dir; I can add this to the PR if you like?

**Comment by Snider** [comment]
Updated PR as requested @sowle 😃

**Comment by sowle** [comment]
Thank you!

**Pull request merged**
